include classpath("application.conf")
node-address { protocol = http, host = "*", port = 9324, context-path = "" }
rest-sqs { enabled = true, bind-hostname = "0.0.0.0", bind-port = 9324, sqs-limits = strict }
rest-stats { enabled = false }
messages-storage { enabled = true, uri = "jdbc:h2:/data/elasticmq" }
queues {
  tourlab-catalog {
    defaultVisibilityTimeout = 60 seconds
    receiveMessageWait = 20 seconds
    deadLettersQueue { name = tourlab-catalog-dlq, maxReceiveCount = 5 }
  }
  tourlab-catalog-dlq { }
  tourlab-reservations {
    defaultVisibilityTimeout = 60 seconds
    receiveMessageWait = 20 seconds
    deadLettersQueue { name = tourlab-reservations-dlq, maxReceiveCount = 5 }
  }
  tourlab-reservations-dlq { }
  tourlab-payments {
    defaultVisibilityTimeout = 60 seconds
    receiveMessageWait = 20 seconds
    deadLettersQueue { name = tourlab-payments-dlq, maxReceiveCount = 5 }
  }
  tourlab-payments-dlq { }
  tourlab-notifications {
    defaultVisibilityTimeout = 60 seconds
    receiveMessageWait = 20 seconds
    deadLettersQueue { name = tourlab-notifications-dlq, maxReceiveCount = 5 }
  }
  tourlab-notifications-dlq { }
}
