// <auto-generated />
using System;
using Catalog.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Catalog.Api.Persistence.Migrations
{
    [DbContext(typeof(CatalogDb))]
    [Migration("20261004171403_Lab005ConfirmationSimulation")]
    partial class Lab005ConfirmationSimulation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Catalog.Api.Persistence.CatalogFault", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Remaining")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Faults", "catalog");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Mode = "None",
                            Remaining = 0
                        });
                });

            modelBuilder.Entity("Catalog.Api.Persistence.CatalogFaultAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("FaultAudit", "catalog");
                });

            modelBuilder.Entity("Catalog.Api.Persistence.CatalogInbox", b =>
                {
                    b.Property<string>("ConsumerName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ConsumerName", "MessageId");

                    b.HasIndex("ProcessedAtUtc");

                    b.ToTable("Inbox", "catalog");
                });

            modelBuilder.Entity("Catalog.Api.Persistence.CatalogOutbox", b =>
                {
                    b.Property<Guid>("DeliveryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EffectKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EnvelopeJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("LeaseOwner")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LeaseUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("DeliveryId");

                    b.HasIndex("Destination", "EffectKey")
                        .IsUnique();

                    b.HasIndex("PublishedAtUtc", "OccurredAtUtc");

                    b.ToTable("Outbox", "catalog");
                });

            modelBuilder.Entity("Catalog.Api.Persistence.Quote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Participants")
                        .HasColumnType("integer");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<long>("TotalAmountMinor")
                        .HasColumnType("bigint");

                    b.Property<long>("UnitAmountMinor")
                        .HasColumnType("bigint");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.HasIndex("SessionId");

                    b.ToTable("Quotes", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_Quote", "\"Participants\" BETWEEN 1 AND 6 AND \"UnitAmountMinor\" > 0 AND \"TotalAmountMinor\" > 0 AND \"Currency\" = 'MXN' AND length(\"UserId\") > 0 AND \"TotalAmountMinor\"::numeric = \"UnitAmountMinor\"::numeric * \"Participants\"");
                        });
                });

            modelBuilder.Entity("Catalog.Api.Persistence.SeatHold", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Participants")
                        .HasColumnType("integer");

                    b.Property<Guid?>("QuoteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RequestFingerprint")
                        .HasColumnType("text");

                    b.Property<Guid?>("ReservationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SagaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("QuoteId")
                        .IsUnique();

                    b.HasIndex("SessionId");

                    b.HasIndex("Status", "ExpiresAtUtc");

                    b.ToTable("Holds", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_Hold", "\"Version\" > 0 AND \"Status\" IN ('Held','Confirmed','Released','Expired','Rejected') AND ((\"SessionId\" IS NULL AND \"QuoteId\" IS NULL AND \"Participants\" = 0 AND \"Status\" IN ('Released','Rejected')) OR (\"SessionId\" IS NOT NULL AND \"QuoteId\" IS NOT NULL AND \"ReservationId\" IS NOT NULL AND \"UserId\" IS NOT NULL AND \"Participants\" BETWEEN 1 AND 6 AND \"ExpiresAtUtc\" IS NOT NULL))");
                        });
                });

            modelBuilder.Entity("Catalog.Api.Persistence.Tour", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Active", "Name", "Id");

                    b.ToTable("Tours", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_Tour", "length(btrim(\"Name\")) > 0 AND \"Version\" > 0");
                        });
                });

            modelBuilder.Entity("Catalog.Api.Persistence.TourSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("integer");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<long>("PriceVersion")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TourId")
                        .HasColumnType("uuid");

                    b.Property<long>("UnitAmountMinor")
                        .HasColumnType("bigint");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TourId", "StartsAtUtc");

                    b.ToTable("Sessions", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_Session", "\"UnitAmountMinor\" > 0 AND \"Currency\" = 'MXN' AND \"Capacity\" >= 0 AND \"AvailableSeats\" >= 0 AND \"AvailableSeats\" <= \"Capacity\" AND \"Version\" > 0 AND \"PriceVersion\" > 0");
                        });
                });

            modelBuilder.Entity("Catalog.Api.Persistence.Quote", b =>
                {
                    b.HasOne("Catalog.Api.Persistence.TourSession", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Catalog.Api.Persistence.SeatHold", b =>
                {
                    b.HasOne("Catalog.Api.Persistence.Quote", null)
                        .WithMany()
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Catalog.Api.Persistence.TourSession", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Catalog.Api.Persistence.TourSession", b =>
                {
                    b.HasOne("Catalog.Api.Persistence.Tour", null)
                        .WithMany()
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
