// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Payments.Api.Persistence;

#nullable disable

namespace Payments.Api.Migrations
{
    [DbContext(typeof(PaymentsDb))]
    [Migration("20261004174208_Lab005RefundRetryGuard")]
    partial class Lab005RefundRetryGuard
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("payments")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Payments.Api.Persistence.PaymentAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Audit", "payments");
                });

            modelBuilder.Entity("Payments.Api.Persistence.PaymentFault", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Remaining")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Faults", "payments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Mode = "Success",
                            Remaining = 0
                        });
                });

            modelBuilder.Entity("Payments.Api.Persistence.PaymentInbox", b =>
                {
                    b.Property<string>("ConsumerName")
                        .HasColumnType("text");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ConsumerName", "MessageId");

                    b.HasIndex("ProcessedAtUtc");

                    b.ToTable("Inbox", "payments");
                });

            modelBuilder.Entity("Payments.Api.Persistence.PaymentOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("bigint");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("LeaseOwner")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LeaseUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("NextReconcileAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProviderReference")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<int>("ReconcileAttempts")
                        .HasColumnType("integer");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SagaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceMessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ReservationId");

                    b.HasIndex("Status", "NextReconcileAtUtc", "LeaseUntilUtc");

                    b.ToTable("Operations", "payments", t =>
                        {
                            t.HasCheckConstraint("CK_Payment", "\"AmountMinor\">0 AND \"Currency\"='MXN' AND \"Version\">0");
                        });
                });

            modelBuilder.Entity("Payments.Api.Persistence.PaymentOutbox", b =>
                {
                    b.Property<Guid>("DeliveryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EffectKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EnvelopeJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("LeaseOwner")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LeaseUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DeliveryId");

                    b.HasIndex("Destination", "EffectKey")
                        .IsUnique();

                    b.HasIndex("PublishedAtUtc", "OccurredAtUtc");

                    b.ToTable("Outbox", "payments");
                });

            modelBuilder.Entity("Payments.Api.Persistence.ProviderEffect", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reference")
                        .HasColumnType("text");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TimeoutDelivered")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("ProviderEffects", "payments");
                });

            modelBuilder.Entity("Payments.Api.Persistence.ProviderRefund", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Failures")
                        .HasColumnType("integer");

                    b.Property<Guid>("PaymentOperationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reference")
                        .HasColumnType("text");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PaymentOperationId")
                        .IsUnique();

                    b.ToTable("ProviderRefunds", "payments");
                });

            modelBuilder.Entity("Payments.Api.Persistence.RefundOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("bigint");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("LastRetryVersion")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("LeaseOwner")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LeaseUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PaymentOperationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProviderReference")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SagaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceMessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PaymentOperationId")
                        .IsUnique();

                    b.HasIndex("Status", "NextAttemptAtUtc");

                    b.ToTable("RefundOperations", "payments", t =>
                        {
                            t.HasCheckConstraint("CK_Refund", "\"AmountMinor\">0 AND \"Currency\"='MXN' AND \"Version\">0");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
